[build]
  base = "apps/api"
  publish = "apps/api/dist"
  command = "cd apps/api && pnpm build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "apps/api/netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
