
[build]
  base = "."
  publish = "dist"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
function = "hello"
path = "/test"

[[edge_functions]]
function = "my-function"
path = "/api/my-function"